% =========================================================================
% Zhicheng Zhang, Xiaokun Liang, Shaode Yu, Yaoqin Xie
% May 25, 2020
% An example to show how to select a FR method for feature ranking 
%    and the data set (BCDR-F03) is from https://bcdr.eu/information/about.
%  
% (1) if the matFR toolbox is useful, please refer to 
%       Zhang, Zhicheng, et al. "matFR: a matlab toolbox for feature ranking"
%
% (2) if using this data set, please refer to 
%       Arevalo, John, et al. "Representation learning for mammography 
%           mass lesion classification with convolutional neural networks." 
%           Computer methods and programs in biomedicine 127 (2016): 248-257.
%       NOTE: Interpretation of the features, please refer to the data set
%
% (3) if using one of these FR methods, please refer to the publication
%
% 
% =========================================================================
clear; close all; clc;
addpath(genpath('FRem'));

miFRmethod = {  'a1_mi_battiti', 'a2_mi_step_wise', ...
                'b1_mi_cond_infomax_learn', ...
                'b2_mi_cond_mutual_info_max', ...
                'b3_mi_mrmr_global', ...
                'b4_mi_max_relevance', ...
                'b5_mi_min_redundancy', ...
                'b6_mi_max_dep_max_rel_min_red', ...
                'b7_mi_quad_program', ...
                'b8_mi_min_redundancy', ...
                'b9_mi_joint', ...
                'c1_mi_giorgio'}; % 12 MI based methods

fnFRmethod = {  'd1_mat_ttest', 'd2_mat_entropy', ...
                'd3_mat_bhattacharyya', 'd4_mat_roc', ...
                'd5_mat_wilcoxon', 'd6_mat_relieff', ...
                'd7_mat_lasso', 'e1_fir_correlation', ...
                'e2_fir_fisher', 'e3_fir_gini', ...
                'e4_fir_KruskalWallis', ...
                'g1_fir_pair_wise_feature_proximity',...
                'g2_fir_max_min_local_structure_info', ...
                'g3_fir_local_learning_clustering', ...
                'g4_fir_L12_regu_discrime', 'g5_fir_eigenvector_centrality', ...
                'g6_fir_infinite_latent', 'g7_fir_concave_minimization', ...
                'g8_fir_infinite', 'g9_fir_ordinal_locality', ...
                'h1_fir_structured_graph_optimization', ...
                'h2_fir_laplacian_score', 'h3_fir_simul_ortho_clustering', ...
                'h4_fir_multi_cluster', 'h5_fir_dependence_guided', ...
                'h6_fir_adaptive_structure_learning', ...
                'k1_fir_joint_embed_learn_sparse_regression', ...
                'k2_fir_spectrum_info_graph_laplacian', ...
                'k3_fir_nonneg_spectral_analysis', ...
                'k4_fir_robust_unsupervised'}; % 30 methods

% -------------------------------------------------------------------------
% (1) load the data set
load bcdr_data_whole
for ii = 1 : length(miFRmethod)
    f = miFRmethod{ii};
    r = matFR_interface(X, f, Y);
end

for jj = 1 : length(fnFRmethod)
    f = fnFRmethod{jj};
    r = matFR_interface(X, f, Y);
end
